function [videoConfDownloadLossRate, ...
    videoConfDownloadExceededDelayRate, ...
    videoConfDownloadDroppedPacketRate, ...
    videoConfDownloadAvgDelay, ...
    videoConfUploadLossRate, ...
    videoConfUploadExceededDelayRate, ...
    videoConfUploadDroppedPacketRate, ...
    videoConfUploadAvgDelay, ...
    cctvLossRate,cctvExceededDelayRate,cctvDroppedPacketRate,cctvAvgDelay] = ...
    importQosResults(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [videoConfDownloadLossRate,videoConfDownloadExceededDelayRate,videoConfDownloadDroppedPacketRate,videoConfDownloadAvgDelay,videoConfUploadLossRate,videoConfUploadExceededDelayRate,videoConfUploadDroppedPacketRate,videoConfUploadAvgDelay,cctvLossRate,cctvExceededDelayRate,cctvDroppedPacketRate,cctvAvgDelay]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [videoConfDownloadLossRate,videoConfDownloadExceededDelayRate,videoConfDownloadDroppedPacketRate,videoConfDownloadAvgDelay,videoConfUploadLossRate,videoConfUploadExceededDelayRate,videoConfUploadDroppedPacketRate,videoConfUploadAvgDelay,cctvLossRate,cctvExceededDelayRate,cctvDroppedPacketRate,cctvAvgDelay]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [videoConfDownloadLossRate,videoConfDownloadExceededDelayRate,videoConfDownloadDroppedPacketRate,videoConfDownloadAvgDelay,videoConfUploadLossRate,videoConfUploadExceededDelayRate,videoConfUploadDroppedPacketRate,videoConfUploadAvgDelay,cctvLossRate,cctvExceededDelayRate,cctvDroppedPacketRate,cctvAvgDelay]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [videoConfDownloadLossRate,videoConfDownloadExceededDelayRate,videoConfDownloadDroppedPacketRate,videoConfDownloadAvgDelay,videoConfUploadLossRate,videoConfUploadExceededDelayRate,videoConfUploadDroppedPacketRate,videoConfUploadAvgDelay,cctvLossRate,cctvExceededDelayRate,cctvDroppedPacketRate,cctvAvgDelay] = importfile('_on0_results.xls','Tabelle1',1,11);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/08/21 19:58:54

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 11;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:L%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:L%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
videoConfDownloadLossRate = data(:,1);
videoConfDownloadExceededDelayRate = data(:,2);
videoConfDownloadDroppedPacketRate = data(:,3);
videoConfDownloadAvgDelay = data(:,4);
videoConfUploadLossRate = data(:,5);
videoConfUploadExceededDelayRate = data(:,6);
videoConfUploadDroppedPacketRate = data(:,7);
videoConfUploadAvgDelay = data(:,8);
cctvLossRate = data(:,9);
cctvExceededDelayRate = data(:,10);
cctvDroppedPacketRate = data(:,11);
cctvAvgDelay = data(:,12);

